### ISSUE TITLE
[UAT] check all teal options

### ISSUE THREAD

**Issue by pawelru** [insightsengineering/teal#438]
- [x] teal.ggplot2_args https://github.com/insightsengineering/teal.devel/issue
- [x] teal.basic_table_args https://github.com/insightsengineering/teal.devel/issue
- [x] teal.load_nest_code 
- [x] teal.log_layout https://github.com/insightsengineering/teal/issues/476
- [x] teal.log_level
- [x] teal_logging depreciated  https://github.com/insightsengineering/teal/issues/475
- [x] teal_show_js_log https://github.com/insightsengineering/teal/issues/478
- [x] teal.threshold_slider_vs_checkboxgroup
- [x] teal_debug https://github.com/insightsengineering/teal/issues/479 REMOVED

Main doc:
https://github.com/insightsengineering/teal/blob/a098e25bbe3e50ffb692032269125b0b054af8b9/vignettes/teal_options.Rmd

General issues:
https://github.com/insightsengineering/teal/issues/477
